### ISSUE TITLE
在进行单张图像预测的时候仍然报错

### ISSUE THREAD

**Issue by gyxxx27** [KyanChen/TTP#1]
报错
Traceback (most recent call last):
  File "D:\TTP\TTP-release\demo\image_demo_with_cdinferencer.py", line 2, in <module>
    from opencd.apis import OpenCDInferencer
ModuleNotFoundError: No module named 'opencd'
是否需要安装opencd库？

**Comment by KyanChen** [comment]
fixed

**Comment by 18810031387** [comment]
python image_demo_with_cdinferencer.py ${C:\00zml\00xiangmu\2023\变化监测\BIT_CD-master\data\lw_building_en_cb_fu\
train\A\211.png} ${C:\00zml\00xiangmu\2023\变化监测\BIT_CD-master\data\lw_building_en_cb_fu\train\B\211.png} configs/TTP/ttp_sam_large_levircd_infer.py --checkpoint ${C:
\00zml\00xiangmu\2023\变化监测\TTP-release\lw\pretrain\epoch_270.pth} --out-dir ${C:\00zml\00xiangmu\2023\变化监测\BIT_CD-master\data\lw_building_en_cb_fu\train} 

File "image_demo_with_cdinferencer.py", line 37, in main
    mmseg_inferencer = OpenCDInferencer(
TypeError: __init__() got multiple values for argument 'classes'                            
 

how can i resolve it?
