### ISSUE TITLE
Try to run Image Prediction code there is an error coming out

### ISSUE THREAD

**Issue by OhSungChoo** [KyanChen/TTP#2]
/data/obama0404/repos/ttplevir/TTP
/data/obama0404/anaconda3/envs/ttplevir/bin/python
moana-r4
Traceback (most recent call last):
  File "demo/image_demo_with_cdinferencer.py", line 57, in <module>
    main()
  File "demo/image_demo_with_cdinferencer.py", line 39, in main
    mmseg_inferencer = OpenCDInferencer(
  File "/data/obama0404/repos/ttplevir/TTP/demo/../opencd/apis/opencd_inferencer.py", line 42, in __init__
    super().__init__(scope=scope, **kwargs)
  File "/data/obama0404/repos/ttplevir/TTP/demo/../mmseg/apis/mmseg_inferencer.py", line 81, in __init__
    super().__init__(
  File "/data/obama0404/anaconda3/envs/ttplevir/lib/python3.8/site-packages/mmengine/infer/infer.py", line 160, in __init__
    cfg, _weights = self._load_model_from_metafile(model)
  File "/data/obama0404/anaconda3/envs/ttplevir/lib/python3.8/site-packages/mmengine/infer/infer.py", line 374, in _load_model_from_metafile
    assert self.scope in MODULE2PACKAGE, (
AssertionError: opencd not in {'mmcls': 'mmcls', 'mmdet': 'mmdet', 'mmdet3d': 'mmdet3d', 'mmseg': 'mmsegmentation', 'mmaction': 'mmaction2', 'mmtrack': 'mmtrack', 'mmpose': 'mmpose', 'mmedit': 'mmedit', 'mmocr': 'mmocr', 'mmgen': 'mmgen', 'mmfewshot': 'mmfewshot', 'mmrazor': 'mmrazor', 'mmflow': 'mmflow', 'mmhuman3d': 'mmhuman3d', 'mmrotate': 'mmrotate', 'mmselfsup': 'mmselfsup', 'mmyolo': 'mmyolo', 'mmpretrain': 'mmpretrain', 'mmagic': 'mmagic'}!,please pass a valid scope.

How can I fix this error?
Thanks.

**Comment by KyanChen** [comment]
Follow the envs setting in Readme

**Comment by OhSungChoo** [comment]
Thanks for the response

I mean I got the results with train.py and test.py

but I don't know why it comes out with error when i run image_demo_with_cdinference.py

Below are my conda list

_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
accelerate                0.27.2                   pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.9.3                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.14.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
altair                    5.2.0                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
blinker                   1.7.0                    pypi_0    pypi
ca-certificates           2023.12.12           h06a4308_0  
cachetools                5.3.3                    pypi_0    pypi
certifi                   2024.2.2                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
cityscapesscripts         2.2.2                    pypi_0    pypi
click                     8.1.7            py38h06a4308_0  
clip                      1.0                       dev_0    <develop>
cmake                     3.28.3                   pypi_0    pypi
codecov                   2.1.13                   pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
coverage                  7.4.3                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
diffusers                 0.26.3                   pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.7.0                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
filelock                  3.13.1                   pypi_0    pypi
flake8                    7.0.0                    pypi_0    pypi
fonttools                 4.49.0                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.2.0                 pypi_0    pypi
ftfy                      6.1.3                    pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.42                   pypi_0    pypi
google-auth               2.28.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
grpcio                    1.62.0                   pypi_0    pypi
huggingface-hub           0.20.3                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.6                      pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imageio-ffmpeg            0.4.2                    pypi_0    pypi
importlib                 1.0.4                    pypi_0    pypi
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.2                    pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
interrogate               1.5.0                    pypi_0    pypi
invisible-watermark       0.2.0                    pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.3.2                    pypi_0    pypi
jsonschema                4.21.1                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kornia                    0.6.0                    pypi_0    pypi
latent-diffusion          0.0.1                     dev_0    <develop>
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
lightning-utilities       0.10.1                   pypi_0    pypi
lit                       17.0.6                   pypi_0    pypi
markdown                  3.5.2                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.7.5                    pypi_0    pypi
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mmcv                      2.1.0                    pypi_0    pypi
mmengine                  0.10.3                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
networkx                  3.1                      pypi_0    pypi
nibabel                   5.2.1                    pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.1.1                    pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openmim                   0.3.9                    pypi_0    pypi
openssl                   3.0.13               h7f8727e_0  
openxlab                  0.0.34                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    2.0.3                    pypi_0    pypi
peft                      0.8.2                    pypi_0    pypi
pillow                    10.2.0                   pypi_0    pypi
pip                       23.3.1           py38h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.2.0                    pypi_0    pypi
pluggy                    1.4.0                    pypi_0    pypi
prettytable               3.10.0                   pypi_0    pypi
protobuf                  4.25.3                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pudb                      2019.2                   pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyarrow                   15.0.0                   pypi_0    pypi
pyasn1                    0.5.1                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycodestyle               2.11.1                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pydeck                    0.8.1b0                  pypi_0    pypi
pydeprecate               0.3.1                    pypi_0    pypi
pyflakes                  3.2.0                    pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
pyquaternion              0.9.9                    pypi_0    pypi
pytest                    8.0.2                    pypi_0    pypi
python                    3.8.18               h955ad1f_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-lightning         1.4.2                    pypi_0    pypi
pytz                      2023.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.33.0                   pypi_0    pypi
regex                     2023.10.3        py38h5eee18b_0  
requests                  2.28.2                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
rpds-py                   0.18.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.4.2                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
sentry-sdk                1.40.5                   pypi_0    pypi
setproctitle              1.3.3                    pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
streamlit                 1.31.1                   pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
taming-transformers       0.0.1                     dev_0    <develop>
tenacity                  8.2.3                    pypi_0    pypi
tensorboard               2.14.0                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
timm                      0.9.16                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tokenizers                0.15.2                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.1                   pypi_0    pypi
torch                     2.0.0                    pypi_0    pypi
torch-fidelity            0.3.0                    pypi_0    pypi
torchaudio                2.0.1                    pypi_0    pypi
torchmetrics              1.3.1                    pypi_0    pypi
torchvision               0.15.1                   pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
tqdm                      4.65.2                   pypi_0    pypi
transformers              4.38.1                   pypi_0    pypi
triton                    2.0.0                    pypi_0    pypi
typing                    3.7.4.3                  pypi_0    pypi
typing-extensions         4.10.0                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
tzlocal                   5.2                      pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
urwid                     2.6.5                    pypi_0    pypi
validators                0.22.0                   pypi_0    pypi
wandb                     0.16.3                   pypi_0    pypi
watchdog                  4.0.0                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
werkzeug                  3.0.1                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0  
xdoctest                  1.1.3                    pypi_0    pypi
xz                        5.4.5                h5eee18b_0  
yapf                      0.40.2                   pypi_0    pypi
yarl                      1.9.4                    pypi_0    pypi
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Comment by KyanChen** [comment]
following the envs configure in readme.
![image](https://github.com/KyanChen/TTP/assets/41983514/7b136fd7-7045-4360-a855-fe342f3396ff)
